FROM registry.access.redhat.com/ubi8/nodejs-16

USER root

RUN npm install --location=global yarn

RUN dnf -y update-minimal --security --sec-severity=Important --sec-severity=Critical && \
    dnf install -y nginx && \
    dnf clean all

ADD . ${APP_ROOT}
WORKDIR ${APP_ROOT}

RUN yarn install && yarn run lint && yarn test 
