---
apiVersion: v1
kind: Template
metadata:
  name: visual-qontract
objects:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: visual-qontract
    name: visual-qontract
    annotations:
      ignore-check.kube-linter.io/minimum-three-replicas: "The internal instance of Visual Qontract does not need 3 replicas"
  spec:
    replicas: ${{REPLICAS}}
    selector:
      matchLabels:
        app: visual-qontract
        deployment: visual-qontract
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
    template:
      metadata:
        labels:
          app: visual-qontract
          deployment: visual-qontract
      spec:
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - visual-qontract
                topologyKey: kubernetes.io/hostname
              weight: 90
            - podAffinityTerm:
                labelSelector:
                  matchExpressions:
                  - key: app
                    operator: In
                    values:
                    - visual-qontract
                topologyKey: topology.kubernetes.io/zone
              weight: 100
        serviceAccountName: visual-qontract
        containers:
        - image: ${IMAGE}:${IMAGE_TAG}
          imagePullPolicy: Always
          name: visual-qontract
          env:
          - name: GRAPHQL_URI
            valueFrom:
              configMapKeyRef:
                key: graphql.uri
                name: visual-qontract
          - name: AUTHORIZATION
            valueFrom:
              secretKeyRef:
                  key: authorization
                  name: visual-qontract
          - name: API_URI
            valueFrom:
              configMapKeyRef:
                key: api.uri
                name: visual-qontract
          - name: API_AUTH
            valueFrom:
              secretKeyRef:
                  key: api.auth
                  name: visual-qontract
          ports:
          - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /graphql?query={__schema{types{name}}}
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /graphql?query={__schema{types{name}}}
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 10
            timeoutSeconds: 3
          resources:
            requests:
              memory: ${MEMORY_REQUESTS}
              cpu: ${CPU_REQUESTS}
            limits:
              memory: ${MEMORY_LIMIT}
              cpu: ${CPU_LIMIT}
          volumeMounts:
            - name: visual-qontract-env
              mountPath: /opt/visual-qontract/build/env/
              readOnly: true
        - image: ${IMAGE_OAUTH2_PROXY}:${IMAGE_OAUTH2_PROXY_TAG}
          imagePullPolicy: Always
          name: visual-qontract-oauth2-proxy
          env:
          - name: OAUTH2_PROXY_REDIRECT_URL
            valueFrom:
              configMapKeyRef:
                key: oauth2.proxy.redirect.url
                name: oauth2-proxy
          - name: OAUTH2_PROXY_COOKIE_SECRET
            valueFrom:
              secretKeyRef:
                  key: oauth2.proxy.cookie.secret
                  name: oauth2-proxy
          - name: OAUTH2_PROXY_CLIENT_ID
            valueFrom:
              secretKeyRef:
                  key: oauth2.proxy.client.id
                  name: oauth2-proxy
          - name: OAUTH2_PROXY_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                  key: oauth2.proxy.client.secret
                  name: oauth2-proxy
          args:
          - --provider=github
          - --https-address=:4180
          - --http-address=
          - --email-domain=*
          - --upstream=http://localhost:8080
          - --tls-cert-file=/etc/tls/private/tls.crt
          - --tls-key-file=/etc/tls/private/tls.key
          - --github-org=app-sre
          - --pass-user-headers
          - --cookie-secret=$(OAUTH2_PROXY_COOKIE_SECRET)
          - --client-id=$(OAUTH2_PROXY_CLIENT_ID)
          - --client-secret=$(OAUTH2_PROXY_CLIENT_SECRET)
          - --redirect-url=$(OAUTH2_PROXY_REDIRECT_URL)
          resources:
            requests:
              memory: ${OAUTH_MEMORY_REQUESTS}
              cpu: ${OAUTH_CPU_REQUESTS}
            limits:
              memory: ${OAUTH_MEMORY_LIMIT}
              cpu: ${OAUTH_CPU_LIMIT}
          ports:
          - containerPort: 4180
          livenessProbe:
            httpGet:
              path: /ping
              port: 4180
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /ping
              port: 4180
            initialDelaySeconds: 3
            periodSeconds: 10
            timeoutSeconds: 3
        volumes:
        - name: visual-qontract-env
          configMap:
            name: visual-qontract
            items:
            - key: env
              path: env.js
- apiVersion: v1
  kind: Service
  metadata:
    name: oauth2-proxy
    labels:
      app: visual-qontract
  spec:
    type: ClusterIP
    ports:
      - name: https
        port: 443
        targetPort: 4180
        protocol: TCP
    selector:
      deployment: visual-qontract
- apiVersion: v1
  kind: Service
  metadata:
    name: visual-qontract
    labels:
      app: visual-qontract
  spec:
    type: ClusterIP
    ports:
      - name: https
        port: 443
        targetPort: 8080
        protocol: TCP
    selector:
      deployment: visual-qontract
parameters:
- name: IMAGE
  value: quay.io/app-sre/visual-qontract
  displayName: visual qontract image
  description: visual qontract docker image. Defaults to quay.io/app-sre/visual-qontract
- name: IMAGE_TAG
  value: latest
  displayName: visual qontract version
  description: visual qontract version which defaults to latest
- name: MEMORY_REQUESTS
  value: 16Mi
- name: MEMORY_LIMIT
  value: 32Mi
- name: CPU_REQUESTS
  value: 10m
- name: CPU_LIMIT
  value: 20m
- name: OAUTH_MEMORY_REQUESTS
  value: 30Mi
- name: OAUTH_MEMORY_LIMIT
  value: 60Mi
- name: OAUTH_CPU_REQUESTS
  value: 10m
- name: OAUTH_CPU_LIMIT
  value: 20m
- name: IMAGE_OAUTH2_PROXY
  value: quay.io/pusher/oauth2_proxy
- name: IMAGE_OAUTH2_PROXY_TAG
  value: v7.4.0-amd64
- name: REPLICAS
  value: '3'
