---
apiVersion: v1
kind: Template
metadata:
  name: visual-qontract
objects:
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: visual-qontract
    name: visual-qontract
  spec:
    replicas: 1
    selector:
      app: visual-qontract
      deploymentconfig: visual-qontract
    strategy:
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: visual-qontract
          deploymentconfig: visual-qontract
      spec:
        containers:
        - image: ${IMAGE}:${IMAGE_TAG}
          imagePullPolicy: Always
          name: visual-qontract
          env:
          - name: GRAPHQL_URI
            valueFrom:
              configMapKeyRef:
                key: graphql.uri
                name: visual-qontract
          - name: AUTHORIZATION
            valueFrom:
              secretKeyRef:
                  key: authorization
                  name: visual-qontract
          - name: API_URI
            valueFrom:
              configMapKeyRef:
                key: api.uri
                name: visual-qontract
          - name: API_AUTH
            valueFrom:
              secretKeyRef:
                  key: api.auth
                  name: visual-qontract
          ports:
          - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /graphql?query={__schema{types{name}}}
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 3
          readinessProbe:
            httpGet:
              path: /graphql?query={__schema{types{name}}}
              port: 8080
            initialDelaySeconds: 3
            periodSeconds: 10
            timeoutSeconds: 3
          resources:
            requests:
              memory: ${MEMORY_REQUESTS}
              cpu: ${CPU_REQUESTS}
            limits:
              memory: ${MEMORY_LIMIT}
              cpu: ${CPU_LIMIT}
          volumeMounts:
            - name: visual-qontract-env
              mountPath: /opt/visual-qontract/build/env/
              readOnly: true
    triggers:
    - type: ConfigChange
- apiVersion: v1
  kind: Service
  metadata:
    name: visual-qontract
    labels:
      app: visual-qontract
  spec:
    type: ClusterIP
    ports:
      - name: https
        port: 443
        targetPort: 8080
        protocol: TCP
    selector:
      deploymentconfig: visual-qontract
parameters:
- name: IMAGE
  value: quay.io/app-sre/visual-qontract
  displayName: visual qontract image
  description: visual qontract docker image. Defaults to quay.io/app-sre/visual-qontract
- name: IMAGE_TAG
  value: latest
  displayName: visual qontract version
  description: visual qontract version which defaults to latest
- name: MEMORY_REQUESTS
  value: 16Mi
- name: MEMORY_LIMIT
  value: 32Mi
- name: CPU_REQUESTS
  value: 10m
- name: CPU_LIMIT
  value: 20m
- name: OAUTH_MEMORY_REQUESTS
  value: 30Mi
- name: OAUTH_MEMORY_LIMIT
  value: 60Mi
- name: OAUTH_CPU_REQUESTS
  value: 10m
- name: OAUTH_CPU_LIMIT
  value: 20m
